services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ../../monitor/notebooks:/workspace/notebooks
      - ../../monitor/data:/workspace/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
